server:
  port: 8081
  servlet:
    context-path: /community



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 19961213lc@@
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mail:
    host: smtp.qq.com
    port: 25
    username: 1445079235@qq.com
    password: hgohrxiylgauiede

  thymeleaf:
    cache: false

  redis:
    database: 0
    host: localhost
    port: 6379



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lican.community.entity

community:
  path:
    domain: http://localhost:8081
    uploadPath: C:/Users/kingtiger/Desktop
